# Generated by Django 5.2.6 on 2025-09-16 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('numero_requisicao', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('prazo_limite', models.DateField()),
                ('setor_solicitante', models.CharField(max_length=100)),
                ('tipo_manutencao', models.CharField(choices=[('ELETRICA', 'Elétrica'), ('MECANICA', 'Mecânica'), ('OUTROS', 'Outros')], max_length=20)),
                ('status_operacional', models.CharField(choices=[('FUNCIONANDO', 'Funcionando'), ('ALERTA', 'Alerta'), ('INOPERANTE', 'Inoperante')], max_length=20)),
                ('equipamentos_impactados', models.JSONField(default=list)),
                ('outros_equipamentos', models.TextField(blank=True)),
                ('titulo_curto', models.CharField(max_length=200)),
                ('descricao_problema', models.TextField()),
                ('prioridade', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('VISUALIZADA', 'Visualizada'), ('ACEITA', 'Aceita'), ('CANCELADA', 'Cancelada'), ('EM_ATENDIMENTO', 'Em atendimento'), ('PARADA', 'Parada'), ('CONCLUIDA', 'Concluída')], default='ABERTA', max_length=20)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('motivo_parada', models.TextField(blank=True)),
                ('data_prevista_termino', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_termino', models.DateTimeField(blank=True, null=True)),
                ('descricao_manutencao', models.TextField(blank=True)),
                ('materiais_utilizados', models.TextField(blank=True)),
                ('responsavel_manutencao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_atendidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancerequest')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('nome_original', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='maintenance.maintenancerequest')),
            ],
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_acao', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='maintenance.maintenancerequest')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_acao'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('COMUM', 'Comum (Requisitante)'), ('MANUTENCAO', 'Manutenção (Recebe Chamado)'), ('GESTOR', 'Gestor (Analisa Dados)'), ('TI', 'T.I (Admin)')], default='COMUM', max_length=20)),
                ('setor', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
